[
  {
    id: 1,
    name: "Dongcheng 1500W 10.5kg Electric Demolition Hammer, DZG10",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/WK1oUs5PKjLz5-large.jpg",
    images: ["https://cdn.moglix.com/p/WK1oUs5PKjLz5-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1500w-105kg-black-electric-demolition-hammer-dzg10/mp/msn8klpmyq8r5v",
    rating: 4.8,
    reviewCount: 19,
    sellingPrice: "₹17,999",
    mrp: "₹19,500",
    discountPercent: "7%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Precised Steel Parts Provides Durable & Long Life",
      "Stable Output Power Under Heavy Load",
    ],
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Dongcheng 750W 5kg Electric Demolition Hammer, DZC03-26B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/t7aTqsoAkSebT-large.jpg",
    images: ["https://cdn.moglix.com/p/t7aTqsoAkSebT-large.jpg"],
    link: "https://www.moglix.com/dongcheng-750w-5kg-electric-demolition-hammer-dzc03-26b/mp/msnpkep4j43d9g",
    rating: 4.2,
    reviewCount: 21,
    sellingPrice: "₹6,188",
    mrp: "₹7,999",
    discountPercent: "22%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["High Quality Material", "Adjustable Speed"],
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Dongcheng DMP02-6 350W Electric Laminate Trimmer",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/9AX5ggSjmXIJA-large.jpg",
    images: ["https://cdn.moglix.com/p/9AX5ggSjmXIJA-large.jpg"],
    link: "https://www.moglix.com/dongcheng-dmp02-6-350w-trimmer/mp/msnrkrem3r039n",
    rating: 4.6,
    reviewCount: 5,
    sellingPrice: "₹2,523",
    mrp: "₹3,423",
    discountPercent: "26%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Extremely Durable",
      "Produces Greater Force Than its Counterparts",
    ],
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Dongcheng DJZ16A 800W 16mm Electric Drill Machine",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/YJFMqUpZmW9O2-large.jpg",
    images: ["https://cdn.moglix.com/p/YJFMqUpZmW9O2-large.jpg"],
    link: "https://www.moglix.com/dongcheng-djz16a-800w-16mm-electric-drill-machine/mp/msne9j8j4o2r9d",
    rating: 4.1,
    reviewCount: 17,
    sellingPrice: "₹3,570",
    mrp: "₹4,356",
    discountPercent: "18%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["24 hrs Dispatch"],
    features: [
      "Drilling with Ac & Dc Electric on Metal, Plastic, Wood",
      "360 Deg Rotated D-Type Handle Ensures Easily Operation",
    ],
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Dongcheng 500W 16000rpm Electric Wood Planer, DMB82",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/aGGFyFSI1npNF-large.jpg",
    images: ["https://cdn.moglix.com/p/aGGFyFSI1npNF-large.jpg"],
    link: "https://www.moglix.com/dongcheng-500w-16000rpm-electric-wood-planer-dmb82/mp/msn4k6zqxx33kq",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,737",
    mrp: "₹4,002",
    discountPercent: "6%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["Top Seller"],
    features: [],
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Dongcheng DZG6S 1050W 6.8 kg Demolition Hammer",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/ElkKlgbxQoJJY-large.jpg",
    images: ["https://cdn.moglix.com/p/ElkKlgbxQoJJY-large.jpg"],
    link: "https://www.moglix.com/dongcheng-dzg6s-1050w-68-kg-percussion-hammer/mp/msnq94p72y4nk0",
    rating: 4.7,
    reviewCount: 7,
    sellingPrice: "₹7,771",
    mrp: "₹8,546",
    discountPercent: "9%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["24 hrs Dispatch"],
    features: [
      "Powerful Motor Makes Quick & Efficient Operation",
      "High Quality Piston Rubber Ring",
    ],
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Dongcheng 300W 125mm Professional Orbital Sander, DSA125",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/00zMf4FEo51Bk-large.jpeg",
    images: ["https://cdn.moglix.com/p/00zMf4FEo51Bk-large.jpeg"],
    link: "https://www.moglix.com/dongcheng-300w-125mm-orbital-sander-dsa125/mp/msn457mezpqn9j",
    rating: 4.0,
    reviewCount: 5,
    sellingPrice: "₹3,261",
    mrp: "₹4,452",
    discountPercent: "26%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["24 hrs Dispatch"],
    features: [
      "Low Vibration & Low Noise",
      "Adjustable Speed & Good Dust Bag Design",
    ],
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Dongcheng 230W Electric Impact Drill Machine, DJZ02-6A",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/QGtMoMYNiW3A7-large.jpg",
    images: ["https://cdn.moglix.com/p/QGtMoMYNiW3A7-large.jpg"],
    link: "https://www.moglix.com/dongcheng-230w-electric-impact-drill-machine-djz02-6a/mp/msn2vsegqgk5jj",
    rating: 4.5,
    reviewCount: 10,
    sellingPrice: "₹1,932",
    mrp: "₹3,449",
    discountPercent: "43%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: ["48 hrs Dispatch"],
    features: [
      "Dongcheng Electric Drill DJZ02-6A Has Variable Speed Ensures Precise Drilling",
      "Ergonomic Soft Grip for Fatigue-Free Drilling",
    ],
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Dongcheng DSB185 160W 10000rpm Blue Orbital Sander",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/G0kmjWy9EeAJl-large.jpg",
    images: ["https://cdn.moglix.com/p/G0kmjWy9EeAJl-large.jpg"],
    link: "https://www.moglix.com/dongcheng-dsb185-160w-10000rpm-blue-orbital-sander/mp/msn457medz2q9j",
    rating: 4.3,
    reviewCount: 3,
    sellingPrice: "₹2,197",
    mrp: "₹4,599",
    discountPercent: "52%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: ["48 hrs Dispatch"],
    features: [
      "Metal Sheet for Better Sanding Result",
      "Low Vibration & Low Noise",
    ],
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Dongcheng DSJ25 25mm 260000rpm 240W Die Grinder",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/3UomcWlnwx5jD-large.jpg",
    images: ["https://cdn.moglix.com/p/3UomcWlnwx5jD-large.jpg"],
    link: "https://www.moglix.com/dongcheng-dsj25-25mm-260000rpm-240w-die-grinder/mp/msnm9xyx2oerkj",
    rating: 4.7,
    reviewCount: 9,
    sellingPrice: "₹2,047",
    mrp: "₹2,500",
    discountPercent: "18%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "It is Also Used for Grinding & Polishing of Varieties",
      "Light Weight",
    ],
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Dongcheng Electric Impact Drill steel capacity 10 mm",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/5DVMUeJsJqAez-large.jpg",
    images: ["https://cdn.moglix.com/p/5DVMUeJsJqAez-large.jpg"],
    link: "https://www.moglix.com/dongcheng-electric-impact-drill-steel-capacity-10-mm/mp/msnr50n464e451",
    rating: 4.8,
    reviewCount: 10,
    sellingPrice: "₹2,195",
    mrp: "₹26,026",
    discountPercent: "91%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: ["Deal of the Day"],
    features: [
      "Reversible Rotation Suitable for Tightening & Loosening Screws",
      "Variable Speed Ensures Precise Drilling",
    ],
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Dongcheng Electric Drill Machine Steel Capacity 10 mm",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/7q6uf8uO9Ua1a-large.jpg",
    images: ["https://cdn.moglix.com/p/7q6uf8uO9Ua1a-large.jpg"],
    link: "https://www.moglix.com/dongcheng-electric-drill-machine-steel-capacity-10-mm/mp/msn153vwlw1jk3",
    rating: 4.4,
    reviewCount: 10,
    sellingPrice: "₹1,815",
    mrp: "₹2,603",
    discountPercent: "30%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Elastic Screws, Electronic Speed Control & Precision Drilling",
      "Optional Keyless Chuck Model",
    ],
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Dongcheng 25mm Die Grinder, DSJ02-25",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/I/9/W/d/MINI9WM1IGS1W-large.jpg",
    images: ["https://cdn.moglix.com/p/I/9/W/d/MINI9WM1IGS1W-large.jpg"],
    link: "https://www.moglix.com/dongcheng-25mm-die-grinder-dsj02-25/mp/msn2r1z0a81t49",
    rating: 4.1,
    reviewCount: 10,
    sellingPrice: "₹2,336",
    mrp: "₹3,920",
    discountPercent: "40%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: ["48 hrs Dispatch"],
    features: [
      "Die Grinder Suits for Processing Cavity Molds, Jigs or Complex",
      "Powerful & Durable",
    ],
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Dongcheng 900W 4 inch Angle Grinder, DSM21-100B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/85xKpTKZtTrme-large.jpg",
    images: ["https://cdn.moglix.com/p/85xKpTKZtTrme-large.jpg"],
    link: "https://www.moglix.com/dongcheng-900w-4-inch-angle-grinder-dsm21-100b/mp/msn2km1qr8lx9v",
    rating: 5.0,
    reviewCount: 2,
    sellingPrice: "₹2,449",
    mrp: "₹3,100",
    discountPercent: "21%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Dust Proof Durability", "Ultra High Speed Precision"],
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Dongcheng 100mm 8500rpm Cordless Angle Grinder with 2 Pcs 20V 4Ah Li-Ion Battery & Charger, DCSM03-100 Type-EM",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/r986u455is5KV-large.png",
    images: ["https://cdn.moglix.com/p/r986u455is5KV-large.png"],
    link: "https://www.moglix.com/dongcheng-100mm-8500rpm-cordless-angle-grinder-with-2-pcs-20v-4ah-li-ion-battery-charger-dcsm03-100-type-em/mp/msne9jpl7eer9d",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹8,299",
    mrp: "₹10,999",
    discountPercent: "24%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["Top Seller"],
    features: ["Auto Stop When Disc Lost Speed", "Brushless Motor"],
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Dongcheng Marble Cutter 110mm DZE02-110",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/j24c9zUlODXaw-large.jpg",
    images: ["https://cdn.moglix.com/p/j24c9zUlODXaw-large.jpg"],
    link: "https://www.moglix.com/dongcheng-marble-cutter-110mm-dze02-110/mp/msn8klpgqpvn5v",
    rating: 4.4,
    reviewCount: 5,
    sellingPrice: "₹3,644",
    mrp: "₹4,150",
    discountPercent: "12%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Comfortable Handling",
      "Solid Body & High Quality Parts Ensure A Longer Service",
    ],
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Dongcheng DZG02-15 1010W Black Corded Electric Demolition Hammer",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/Tu3zxU5ZLULbg-large.jpg",
    images: ["https://cdn.moglix.com/p/Tu3zxU5ZLULbg-large.jpg"],
    link: "https://www.moglix.com/dongcheng-dzg02-15-1010w-black-corded-electric-demolition-hammer/mp/msng9vng8m3dkp",
    rating: 4.6,
    reviewCount: 5,
    sellingPrice: "₹17,499",
    mrp: "₹21,345",
    discountPercent: "18%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Used to Concrete Crushing, Chipping, Digging & Cutting",
      "Widely Applied in Pipes Assembling, Cables Laying, Machinery Installation, Water",
    ],
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Dongcheng 1500W Armature for 10kg DZG10/11E Percussion Hammer & Hand Tool Kit",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/FUYNuRHh1SMYp-large.jpg",
    images: ["https://cdn.moglix.com/p/FUYNuRHh1SMYp-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1500w-armature-for-10kg-dzg10-11e-percussion-hammer-hand-tool-kit/mp/msn4k6yoy7839q",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹1,822",
    mrp: "₹2,999",
    discountPercent: "39%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Dongcheng DJC30 19mm 900W 450rpm Magnetic Drill with 30mm Drill Capacity",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/75ajArCQ4X6JR-large.jpg",
    images: ["https://cdn.moglix.com/p/75ajArCQ4X6JR-large.jpg"],
    link: "https://www.moglix.com/dongcheng-djc30-19mm-900w-450rpm-magnetic-drill-with-30mm-drill-capacity/mp/msnz52626j8m9x",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹18,540",
    mrp: "₹25,000",
    discountPercent: "25%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["Top Seller"],
    features: [
      "Smooth & Fatigue-Free Drilling",
      "Flexible for Site Installation & Aerial Work",
    ],
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Dongcheng 5 inch Angle Grinder",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/HyhnHrQJIwhtA-large.jpg",
    images: ["https://cdn.moglix.com/p/HyhnHrQJIwhtA-large.jpg"],
    link: "https://www.moglix.com/dongcheng-5-inch-angle-grinder/mp/msnz5267j1dm9x",
    rating: 4.7,
    reviewCount: 6,
    sellingPrice: "₹3,999",
    mrp: null,
    discountPercent: null,
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["48 hrs Dispatch"],
    features: [
      "Pure Copper Armature & High Quality Material Ergonomical Design",
      "Compact & Easy to Operate",
    ],
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Dongcheng 10.8V 2.0Ah Cordless Drill Drivers, DCJZ1202E",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/L4woo7g8yCoKz-large.jpg",
    images: ["https://cdn.moglix.com/p/L4woo7g8yCoKz-large.jpg"],
    link: "https://www.moglix.com/dongcheng-108v-20ah-cordless-drill-drivers-dcjz1202e/mp/msno5wnj1o6r51",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,924",
    mrp: "₹3,800",
    discountPercent: "23%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Compact & Lightweight Design",
      "Powerful & Long-lasting Battery",
    ],
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Dongcheng 1400W 7kg Percussion Hammer, DZG06-6S",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/PvrYfBYt5MPfq-large.jpg",
    images: ["https://cdn.moglix.com/p/PvrYfBYt5MPfq-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1400w-7kg-percussion-hammer-dzg06-6s/mp/msn39yrnddel5q",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹7,925",
    mrp: "₹8,487",
    discountPercent: "6%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Dongcheng DPB12 (P1B-FF-12) Electric Impact Wrench",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/J/H/H/d/MINJHHF0IU70W-large.jpg",
    images: ["https://cdn.moglix.com/p/J/H/H/d/MINJHHF0IU70W-large.jpg"],
    link: "https://www.moglix.com/dongcheng-dpb12-p1b-ff-12-electric-impact-wrench/mp/msn2vs4984cxdr",
    rating: 4.0,
    reviewCount: 1,
    sellingPrice: "₹3,573",
    mrp: "₹8,150",
    discountPercent: "56%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["48 hrs Dispatch"],
    features: [
      "It Comes with Insert Bits",
      "The Set Also Consists of a Screw Driver Tool Kit",
    ],
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Dongcheng 1050W 110mm Handheld Marble Cutter, DZE03-110",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/JBkfv2fC9C7tq-large.jpg",
    images: ["https://cdn.moglix.com/p/JBkfv2fC9C7tq-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1050w-110mm-handheld-marble-cutter-dze03-110/mp/msnr50ne378451",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,796",
    mrp: "₹4,300",
    discountPercent: "11%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Heavy Duty", "Larger Blade Guard Ensures Higher Safety"],
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Dongcheng 12.7mm 358Nm Cordless Brushless Impact Wrench with 2 Pcs 20V 4Ah Battery & Charger, DCPB358 Type-EM",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/vkFhHb5glPKGP-large.jpg",
    images: ["https://cdn.moglix.com/p/vkFhHb5glPKGP-large.jpg"],
    link: "https://www.moglix.com/dongcheng-127mm-358nm-cordless-brushless-impact-wrench-with-2-pcs-20v-4ah-battery-charger-dcpb358-type-em/mp/msnekppwdoowk2",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹6,999",
    mrp: "₹9,999",
    discountPercent: "30%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "2 Speed Settings",
      "High-efficiency Cooling Vents, which Effectively Extend the Product's Lifespan",
    ],
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Dongcheng 4 inch 800W Angle Grinder, DSM08-100",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/8PxBSJZIvXWXf-large.jpg",
    images: ["https://cdn.moglix.com/p/8PxBSJZIvXWXf-large.jpg"],
    link: "https://www.moglix.com/dongcheng-4-inch-800w-angle-grinder-dsm08-100/mp/msnr50ndep4451",
    rating: 4.0,
    reviewCount: 5,
    sellingPrice: "₹2,464",
    mrp: "₹3,100",
    discountPercent: "20%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: ["48 hrs Dispatch"],
    features: [],
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Dongcheng 500W 20mm Keyless Hammer Drill, DZC02-20",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/VW0RfaW9jmVGO-large.jpg",
    images: ["https://cdn.moglix.com/p/VW0RfaW9jmVGO-large.jpg"],
    link: "https://www.moglix.com/dongcheng-500w-20mm-keyless-hammer-drill-dzc02-20/mp/msnekpq6zgny52",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹4,879",
    mrp: "₹5,400",
    discountPercent: "9%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Optimized Transmission Mechanism Design Ensures Excellent Performance",
      "Combination of Hammer & Drill Makes It Multi-Purpose",
    ],
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Dongcheng 12.7mm 294Nm 340W 1700rpm Electric Impact Wrench, DPB20C",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/Fp3gcAJDhiqKC-large.jpg",
    images: ["https://cdn.moglix.com/p/Fp3gcAJDhiqKC-large.jpg"],
    link: "https://www.moglix.com/dongcheng-127mm-294nm-340w-1700rpm-electric-impact-wrench-dpb20c/mp/msng9ve27qqdkp",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹4,694",
    mrp: "₹9,999",
    discountPercent: "53%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Long-lasting", "Light Weight & Rubber Covered Front"],
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Dongcheng 90mm 1350W 2300rpm Core Drill Machine, DZZ90",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/U3smOXVwSZl8Q-large.jpg",
    images: ["https://cdn.moglix.com/p/U3smOXVwSZl8Q-large.jpg"],
    link: "https://www.moglix.com/dongcheng-90mm-1350w-2300rpm-core-drill-machine-dzz90/mp/msnm9xnxgzzd5j",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹6,899",
    mrp: "₹8,604",
    discountPercent: "19%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Aluminium Housing & Adjustable Speed", "Long Motor Life"],
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Dongcheng 22mm 1400rpm Cordless Rotary Hammer with 2 Pcs 20V 4Ah Li-Ion Battery & Charger, DCZC22 Type-BM",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/5UggK9Mb3vnFf-large.jpg",
    images: ["https://cdn.moglix.com/p/5UggK9Mb3vnFf-large.jpg"],
    link: "https://www.moglix.com/dongcheng-22mm-1400rpm-cordless-rotary-hammer-with-2-pcs-20v-4ah-li-ion-battery-charger-dczc22-type-bm/mp/msnr50xj41m291",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹8,947",
    mrp: "₹11,950",
    discountPercent: "25%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["Top Seller"],
    features: [
      "Electronic Constant Speed Control, Maintains Constant Speed Under Load",
      "Adjustable Speed, Forward and Reverse Rotation",
    ],
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Dongcheng 100x110mm 240W 14000rpm Orbital Sander, DSB 03-100S",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/m8cL1ZXRxe5H3-large.jpg",
    images: ["https://cdn.moglix.com/p/m8cL1ZXRxe5H3-large.jpg"],
    link: "https://www.moglix.com/dongcheng-100x110mm-240w-14000rpm-orbital-sander-dsb-03-100s/mp/msn39yjmjpxl9q",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,285",
    mrp: "₹2,999",
    discountPercent: "23%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: ["Top Seller"],
    features: [
      "Low Vibration Design, Upgraded Efficiency & Lifetime",
      "Rubber-covered Body & Comfortable to Grip",
    ],
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Dongcheng 38mm 1100W 320rpm Electric Rotary Hammer, DZC03-38",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/Ktv7DgvUwbo3b-large.jpg",
    images: ["https://cdn.moglix.com/p/Ktv7DgvUwbo3b-large.jpg"],
    link: "https://www.moglix.com/dongcheng-38mm-1100w320rpm-electric-rotary-hammer-dzc03-38/mp/msne5nle34wy9l",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹12,308",
    mrp: "₹17,388",
    discountPercent: "29%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Afet Clutch Design & Effectively Protect the Safety of the",
      "High-strength Metal Shell Design",
    ],
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Dongcheng 25.4mm 900Nm 1050W 1400rpm Electric Impact Wrench, DPB30",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/tVaqQPuRwrxey-large.jpg",
    images: ["https://cdn.moglix.com/p/tVaqQPuRwrxey-large.jpg"],
    link: "https://www.moglix.com/dongcheng-254mm-900nm-1050w-1400rpm-electric-impact-wrench-dpb30/mp/msne9jpl7eyr9d",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹13,349",
    mrp: "₹17,999",
    discountPercent: "25%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Rubber-covered Front", "Rocker Type Reversing Switch"],
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Dongcheng 500W 13mm Electric Impact Drill, DZJ03-13",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/rc0NccrvsQ6qV-large.jpg",
    images: ["https://cdn.moglix.com/p/rc0NccrvsQ6qV-large.jpg"],
    link: "https://www.moglix.com/dongcheng-500w-13mm-electric-impact-drill-dzj03-13/mp/msne5n8zq7x0kl",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,487",
    mrp: "₹4,200",
    discountPercent: "16%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Smooth Hammering & Drilling Functions",
      "Variable Speed Ensures Precise Drilling",
    ],
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Dongcheng 2000W 500lpm Heat Gun, DQB05-2000",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/99e53QcM28Lci-large.jpg",
    images: ["https://cdn.moglix.com/p/99e53QcM28Lci-large.jpg"],
    link: "https://www.moglix.com/dongcheng-2000w-500lpm-heat-gun-dqb05-2000/mp/msno5wlxwqqw91",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹1,508",
    mrp: "₹2,999",
    discountPercent: "49%",
    coupon: null,
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Dual Heating Coil", "3-Gear Temperature & Air Flow Adjustment"],
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Dongcheng 500W 13mm Electric Impact Drill, DZJ02-13",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/g4ZncXgZhuMnC-large.jpg",
    images: ["https://cdn.moglix.com/p/g4ZncXgZhuMnC-large.jpg"],
    link: "https://www.moglix.com/dongcheng-500w-13mm-electric-impact-drill-dzj02-13/mp/msn153vo4e0jk3",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,451",
    mrp: "₹3,400",
    discountPercent: "27%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Reversible Rotation Suitable for Tightening & Loosening Screws",
      "Smooth Hammering & Drilling Functions",
    ],
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Dongcheng 710W 4 inch Angle Grinder, DSM03-100A",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/1FSeWdEhZj12D-large.jpg",
    images: ["https://cdn.moglix.com/p/1FSeWdEhZj12D-large.jpg"],
    link: "https://www.moglix.com/dongcheng-710w-4-inch-angle-grinder-dsm03-100a/mp/msne5n8zq7n0kl",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,172",
    mrp: "₹3,050",
    discountPercent: "28%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Powerful & Durable Motor",
      "Robust Quality & Rugged Reliability",
    ],
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Dongcheng 1200W 125mm Blue Angle Grinder, DSM02-125B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/cTAlS9yuMd6ej-large.jpg",
    images: ["https://cdn.moglix.com/p/cTAlS9yuMd6ej-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1200w-125mm-blue-angle-grinder-dsm02-125b/mp/msnr50neool251",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,808",
    mrp: "₹3,999",
    discountPercent: "4%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Dongcheng 5Nm 4V 300rpm Cordless Screwdriver, DCPL04-5 Type-E",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/S5MNaV3Spn3nY-large.jpg",
    images: ["https://cdn.moglix.com/p/S5MNaV3Spn3nY-large.jpg"],
    link: "https://www.moglix.com/dongcheng-5nm-4v-300rpm-cordless-screwdriver-dcpl04-5-type-e/mp/msnpkezq2jjdkg",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹1,899",
    mrp: "₹2,999",
    discountPercent: "36%",
    coupon: null,
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Small & Compact", "3-Gear Torque Adjustment"],
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Dongcheng 3/4 inch 20V Brushless Cordless Impact Wrench with 2 Battery, DCPB-1288",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/ZlIPDpPH2TVnz-large.jpg",
    images: ["https://cdn.moglix.com/p/ZlIPDpPH2TVnz-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1-2-inch-20v-cordless-impact-wrench-with-2-battery-dcpb-1288/mp/msnnkqyvo8nz9x",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹15,599",
    mrp: "₹21,999",
    discountPercent: "29%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Dongcheng 50mm 620W 1600spm Rated Stroke Electric Shear, DJJ32",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/k5luNcWHUYw1S-large.jpg",
    images: ["https://cdn.moglix.com/p/k5luNcWHUYw1S-large.jpg"],
    link: "https://www.moglix.com/dongcheng-50mm-620w-1600-min-rated-stroke-electric-shear-djj32/mp/msnnkqyv2mev9x",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹7,463",
    mrp: "₹9,999",
    discountPercent: "25%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["High Power", "Convenient for Long Time Shearing"],
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Dongcheng 12.7mm 488Nm Cordless Brushless Impact Wrench with 2 Pcs 20V 4Ah Battery & Charger, DCPB488 Type-EM",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/iJHxpD3IvjCco-large.jpg",
    images: ["https://cdn.moglix.com/p/iJHxpD3IvjCco-large.jpg"],
    link: "https://www.moglix.com/dongcheng-127mm-488nm-cordless-brushless-impact-wrench-with-2-pcs-20v-4ah-battery-charger-dcpb488-type-em/mp/msnpkezq2j7dkg",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹7,399",
    mrp: "₹9,999",
    discountPercent: "26%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "High-efficiency Cooling Vents, which Effectively Extend the Product's Lifespan",
      "3 Speed Settings",
    ],
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Dongcheng 110mm 1800W 13500rpm Marble Cutter, DZE06-110",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/Htgj301lZeGnh-large.jpg",
    images: ["https://cdn.moglix.com/p/Htgj301lZeGnh-large.jpg"],
    link: "https://www.moglix.com/dongcheng-110mm-1800w-13500rpm-marble-cutter-dze06-110/mp/msn39yjmeq2l9q",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,880",
    mrp: "₹5,999",
    discountPercent: "35%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Anti-splash Board Design",
      "Trigger Switch with Lock-on Button",
    ],
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Dongcheng 13mm 500W 1450rpm Electric Drill Machine, DJZ02-13",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/sMYseLlpOoR2O-large.jpg",
    images: ["https://cdn.moglix.com/p/sMYseLlpOoR2O-large.jpg"],
    link: "https://www.moglix.com/dongcheng-13mm-500w-1450rpm-electric-drill-machine-djz02-13/mp/msn4k6yo32w39q",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,800",
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Variable Speed Ensures Precise Drilling",
      "Reversible Rotation is Suitable for Tightening & Loosening Screws",
    ],
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Dongcheng 125mm 1800W 13000rpm Marble Cutter Machine, DZE03-125",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/ODXjVihGfAMTe-large.jpg",
    images: ["https://cdn.moglix.com/p/ODXjVihGfAMTe-large.jpg"],
    link: "https://www.moglix.com/dongcheng-125mm-1800w-13000rpm-marble-cutter-machine-dze03-125/mp/msnnkqg7xx2v9x",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,746",
    mrp: "₹3,876",
    discountPercent: "3%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Dongcheng 250W 10mm Keyless Electric Drill Machine, DJZ08-10",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/rwJYBc7qQoXvy-large.jpg",
    images: ["https://cdn.moglix.com/p/rwJYBc7qQoXvy-large.jpg"],
    link: "https://www.moglix.com/dongcheng-250w-10mm-keyless-electric-drill-machine-djz08-10/mp/msnq94p2d3enk0",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,643",
    mrp: "₹3,700",
    discountPercent: "28%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "Reversible Rotation Suitable for Tightening & Loosening Screws",
      "Variable Speed Ensures Precise Drilling",
    ],
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Dongcheng 12.7mm 698Nm Cordless Brushless Impact Wrench with 2 Pcs 20V 5Ah Battery & Charger, DCPB698 Type-FK",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/boEF6Z4iTG8Bv-large.jpg",
    images: ["https://cdn.moglix.com/p/boEF6Z4iTG8Bv-large.jpg"],
    link: "https://www.moglix.com/dongcheng-127mm-698nm-cordless-brushless-impact-wrench-with-2-pcs-20v-5ah-battery-charger-dcpb698-type-fk/mp/msn2km6gev785v",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹12,465",
    mrp: "₹17,399",
    discountPercent: "28%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [
      "4 Speed Settings",
      "High-efficiency Cooling Vents, which Effectively Extend the Product's Lifespan",
    ],
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Dongcheng 1/2 inch 20V 298Nm Cordless Impact Wrench with 2 Battery, DCPB298",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/EK3IKBZspgdVw-large.jpg",
    images: ["https://cdn.moglix.com/p/EK3IKBZspgdVw-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1-2-inch-20v-cordless-impact-wrench-with-2-battery-dcpb298/mp/msne9jpln2x09d",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹6,599",
    mrp: "₹12,800",
    discountPercent: "48%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Dongcheng 1850W 22000rpm Electric Wood Router, DMR04-12",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/fE5l6OpGTEw70-large.jpg",
    images: ["https://cdn.moglix.com/p/fE5l6OpGTEw70-large.jpg"],
    link: "https://www.moglix.com/dongcheng-1850w-22000rpm-electric-wood-router-dmr04-12/mp/msn4k6yo32v39q",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹6,018",
    mrp: "₹9,999",
    discountPercent: "39%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: ["Top Seller"],
    features: [],
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Dongcheng 800W 14mm Blue Rotary Hammer Drill, DZC05-26B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/KpOKKAclruPKT-large.jpg",
    images: ["https://cdn.moglix.com/p/KpOKKAclruPKT-large.jpg"],
    link: "https://www.moglix.com/dongcheng-800w-14mm-blue-rotary-hammer-drill-dzc05-26b/mp/msne9j8orrdr9d",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹5,260",
    mrp: "₹5,462",
    discountPercent: "3%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Dongcheng 235mm 2000W Blue Angle Circular Saw, DMY02-235",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/2uBFKIZ5W6pm3-large.jpg",
    images: ["https://cdn.moglix.com/p/2uBFKIZ5W6pm3-large.jpg"],
    link: "https://www.moglix.com/dongcheng-235mm-2000w-blue-angle-circular-saw-dmy02-235/mp/msn4k6zqxx03kq",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹7,188",
    mrp: "₹7,830",
    discountPercent: "8%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Dongcheng 620W Blue Heat Gun, DQB2000",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/p/qXc2SHGS1J7TW-large.jpg",
    images: ["https://cdn.moglix.com/p/qXc2SHGS1J7TW-large.jpg"],
    link: "https://www.moglix.com/dongcheng-620w-blue-heat-gun-dqb2000/mp/msnm9xyrvmpmkj",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹1,690",
    mrp: "₹2,600",
    discountPercent: "35%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: ["Easy to Use & Carry"],
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Dongcheng 105W 10mm Blue Die Grinder, DSJ03-10",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-105w-10mm-blue-die-grinder-dsj03-10/mp/msnm9xyr44odkj",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹1,987",
    mrp: "₹2,102",
    discountPercent: "5%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Dongcheng 25mm 26000rpm 240W Die Grinder, DSJ25B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-25mm-26000rpm-240w-die-grinder-dsj25b/mp/msnv5o670dwvk6",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹1,688",
    mrp: "₹2,225",
    discountPercent: "24%",
    coupon: null,
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: ["Top Seller"],
    features: [],
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Dongcheng 1100W 4 inch Blue Angle Grinder, DSM17-100",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-1100w-4-inch-blue-angle-grinder-dsm17-100/mp/msno5wnjvvyw51",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,576",
    mrp: "₹2,768",
    discountPercent: "6%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Dongcheng 26mm 20V Cordless Brushless Rotary Hammer with Battery & Charger, DCZC02-26",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-26mm-20v-cordless-brushless-rotary-hammer-with-battery-charger-dczc02-26/mp/msnr50neoop251",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹11,899",
    mrp: "₹15,248",
    discountPercent: "21%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Dongcheng 710W 5300rpm Blue Straight Grinder, DSS125B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-710w-5300rpm-blue-straight-grinder-dss125b/mp/msnv5oopxx0v56",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹4,947",
    mrp: "₹5,114",
    discountPercent: "3%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Dongcheng 180mm 2200W 8300rpm Angle Grinder, DSM180A",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-180mm-2200w-8300rpm-angle-grinder-dsm180a/mp/msn457pxyjjq9j",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹6,183",
    mrp: "₹7,310",
    discountPercent: "15%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Dongcheng 560W 4 inch Blue Angle Grinder, DSM04-100A",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-560w-4-inch-blue-angle-grinder-dsm04-100a/mp/msn39yrnddyl5q",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,219",
    mrp: "₹2,316",
    discountPercent: "4%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Dongcheng 200mm 700rpm 3500W Diamond Drill, DZZ02-200S",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-200mm-700rpm-3500w-diamond-drill-dzz02-200s/mp/msnnkqyv2m1v9x",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹28,967",
    mrp: "₹29,999",
    discountPercent: "3%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Dongcheng 300W 1/2 inch Corded Impact Wrench, DPB12",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-300w-1-2-inch-corded-impact-wrench-dpb12/mp/msnq94p200yek0",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,778",
    mrp: "₹3,965",
    discountPercent: "4%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Dongcheng 780W 13000rpm Angle Grinder, DSM04-100B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-780w-13000rpm-angle-grinder-dsm04-100b/mp/msnnkqyvyndv9x",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹2,427",
    mrp: "₹3,999",
    discountPercent: "39%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Dongcheng 620W 3/4 inch Electric Corded Impact Wrench, DPB22C",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-620w-3-4-inch-electric-corded-impact-wrench-dpb22c/mp/msnpkep8oo2d9g",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹6,854",
    mrp: "₹8,267",
    discountPercent: "17%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Dongcheng 16mm 900W 450rpm Magnetic Drill, DJC16",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-16mm-900w-450rpm-magnetic-drill-djc16/mp/msnnkqyv2mjv9x",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹16,725",
    mrp: "₹19,000",
    discountPercent: "11%",
    coupon: null,
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Dongcheng 300W Electric Drill, DJZ10A",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-300w-electric-drill-djz10a/mp/msnm9xyxzedrkj",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹1,910",
    mrp: "₹2,050",
    discountPercent: "6%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: null,
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Dongcheng 160mm 800W Electric Paint Mixer, DQU160",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-160mm-800w-electric-paint-mixer-dqu160/mp/msnm9xyr441dkj",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹3,856",
    mrp: "₹4,193",
    discountPercent: "8%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Dongcheng 300W 8mm Blue Electric Screw Driver, DPL8",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-300w-8mm-blue-electric-screw-driver-dpl8/mp/msnq94p2004ek0",
    rating: null,
    reviewCount: null,
    sellingPrice: "₹4,094",
    mrp: "₹4,322",
    discountPercent: "5%",
    coupon: "flat Rs. 50 OFF with coupon",
    emi: "Easy EMI available",
    deliveryDate: "Thursday, 30 July",
    tags: [],
    features: [],
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Dongcheng Electric Planner 500 W",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-electric-planner-500-w/mp/msn8580v2zn492",
    rating: 4.2,
    reviewCount: 12,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: ["24 hrs Dispatch"],
    features: [
      "Does Not Lose its Properties Under High Load",
      "Produces Greater Force than its Counterparts",
    ],
    availability: "Available on Request",
  },
  {
    id: 69,
    name: "Dongcheng Electric Planner 570 W",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-electric-planner-570-w/mp/msnl5glz826yk4",
    rating: 4.0,
    reviewCount: 1,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [],
    availability: "Available on Request",
  },
  {
    id: 70,
    name: "Dong Cheng 355mm 200W Electric Cut Off Machine with High-Speed Steel Blade, DJG02-355",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dong-cheng-355mm-200w-electric-cut-off-machine-with-high-speed-steel-blade-djg02-355/mp/msnv5oopxx4v56",
    rating: null,
    reviewCount: null,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [],
    availability: "Available on Request",
  },
  {
    id: 71,
    name: "Dongcheng Marble Cutter 110mm FF02-110",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-marble-cutter-110mm-ff02-110/mp/msn8580vy02l92",
    rating: 4.2,
    reviewCount: 10,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: ["48 hrs Dispatch"],
    features: [
      "Highly Durable",
      "Through its Circular Saw, The Marble Cutter by Dongcheng can",
    ],
    availability: "Available on Request",
  },
  {
    id: 72,
    name: "Dongcheng 850W 801 Angle Grinder, S1M-FF05-100B",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-850w-801-angle-grinder-s1m-ff05-100b/mp/msn2qv5zwm6dr7",
    rating: 4.3,
    reviewCount: 11,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [
      "Good Quality & Long Lasting",
      "Suits for Normal Circumstance, Which Could Operate for Metal Parts",
    ],
    availability: "Available on Request",
  },
  {
    id: 73,
    name: "Dongcheng 9 inch Angle Grinder",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-9-inch-angle-grinder/mp/msn19z234xr353",
    rating: 4.4,
    reviewCount: 10,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: ["48 hrs Dispatch"],
    features: ["Efficient", "Compact"],
    availability: "Available on Request",
  },
  {
    id: 74,
    name: "Dongcheng 600W Electric Impact Drill Machine, J1Z-FF02-10",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-600w-electric-impact-drill-machine-j1z-ff02-10/mp/msn2vsfqo9z7bd",
    rating: 5.0,
    reviewCount: 1,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [],
    availability: "Available on Request",
  },
  {
    id: 75,
    name: "Dongcheng 1400W 150mm Blue Groove Cutter, DZR02-150",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-1400w-150mm-blue-groove-cutter-dzr02-150/mp/msn457mznn1q9j",
    rating: null,
    reviewCount: null,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [],
    availability: "Available on Request",
  },
  {
    id: 76,
    name: "Dongcheng Spiral Electric Mixer",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-spiral-electric-mixer/mp/msn457my110q9j",
    rating: 4.6,
    reviewCount: 5,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [
      "360 deg Free Rotation D-Shaped Handle, Easy to Operate",
      "Storage & Maintenance",
    ],
    availability: "Available on Request",
  },
  {
    id: 77,
    name: "Dongcheng Hammer Drill 500 W",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-hammer-drill-500-w/mp/msnv5oo046gv56",
    rating: 4.3,
    reviewCount: 10,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: ["Exclusive Diy Engineers Product", "The Vibrations are Low"],
    availability: "Available on Request",
  },
  {
    id: 78,
    name: "Dongcheng DSB100 150W 12000rpm Orbital Sander",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-dsb100-150w-12000rpm-orbital-sander/mp/msn4k6zg4qm3kq",
    rating: 4.6,
    reviewCount: 5,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: ["48 hrs Dispatch"],
    features: [
      "Dongcheng Sanders Has A Combination of Lower Vibration & Effective",
      "With This Sanders, Pinch Points are Eliminated by Using A",
    ],
    availability: "Available on Request",
  },
  {
    id: 79,
    name: "Dongcheng Electric Drill Steel Capacity 6.5 mm",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-electric-drill-steel-capacity-65-mm/mp/msn2km1e4eqx9v",
    rating: 4.1,
    reviewCount: 10,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [
      "Reversible Rotation Suitable for Tightening & Loosening Screws",
      "Variable Speed Ensures Precise Drilling",
    ],
    availability: "Available on Request",
  },
  {
    id: 80,
    name: "Dongcheng Straight Sander 5300 rpm",
    brand: "Dongcheng",
    image: "https://cdn.moglix.com/assets/img/home_card.webp",
    images: ["https://cdn.moglix.com/assets/img/home_card.webp"],
    link: "https://www.moglix.com/dongcheng-straight-sander-5300-rpm/mp/msnr50n46j6251",
    rating: 4.3,
    reviewCount: 6,
    sellingPrice: null,
    mrp: null,
    discountPercent: null,
    coupon: null,
    emi: null,
    deliveryDate: null,
    tags: [],
    features: [
      "Exclusive Diy Engineers Product",
      "Light Body with Comfortable Hand Feeling",
    ],
    availability: "Available on Request",
  },
];
